In [1]:
!pip install -q oauth2client==1.5.2
import sys
sys.path.append("./utils/student_function/")
from mooclib import *
import inspect, urllib
html, auth_code, userinfo = google_authenticate(PORT_NUMBER=8080)
html

ImportError: ignored

## Ejercicio 1

Una matriz diagonal 2D es aquella en la que cualquier elemento $m_{ij}=0 \iff i \ne j$.  Trataremos solamente con matrices cuadradas, es decir $\in \mathbb{R}^{n \times n}$.

Si asumimos que solo tenemos matrices cuadradas, podemos **almacenar solo la diagonal**.

Completa la siguiente función para que, dado un array `numpy` de entrada:

- Lance un `AssertionError` si no es cuadrado o no es diagonal
- Devuelva un vector con las posiciones de almacenamiento de su diagonal, asumiendo una posición inicial y un tamaño de dato.

Por ejemplo, para esta entrada:

    [[ 1  0  0]
     [ 0  3  0]
     [ 0  0 -3]]

con `init_pos=19` y `size=5`, la salida debería de ser:

    [19, 24, 29]

In [0]:
import numpy as np
a = np.array([[1,2,4], [5,3,6], [7,8,-3]])
b=[19]
for i in range(a.shape[0]-1):
    for j in range(a.shape[0]-1):
        if i=j:
            b+=[b[i]+5]
print b

[19, 24, 29, 29]


In [0]:
%%writefile ./utils/student_function/PS04_01.py
import numpy as np
def diag_store(a, init_pos=0, size=4):
    assert (a.shape[0]==a.shape[1]) and (np.array_equal(a,np.diag(np.diag(a))))
    b=[init_pos]
    for i in range(a.shape[0]-1):
        for j in range(a.shape[0]-1):
            if i==j:
                b+=[b[i]+size]
    return b

Overwriting ./utils/student_function/PS04_01.py


comprueba manualmente tu código

In [0]:
import PS04_01 as st
reload(st)
import numpy as np

a = np.array([[1,0,0], [0,3,0], [0,0,-3]])
print a
st.diag_store(a, init_pos=19, size=5)


[[ 1  0  0]
 [ 0  3  0]
 [ 0  0 -3]]


[19, 24, 29]

#### comprueba tu código con el corrector automático

In [0]:
!./run CHECK_SOLUTION PS04_01

checking your code with 100 random calls
** CORRECTO **
evaluation result 5.0 


#### registra tu solución en línea

In [0]:
!./run SUBMIT_SOLUTION PS04_01

connecting ... registering submission for daniel.riveraa@udea.edu.co ...
no config found for section PS04, allowing all submissions
checking your code with 100 random calls
** CORRECTO **
your submissions sheet is https://docs.google.com/spreadsheets/d/1QjA5eGBEkEfHxuQDJaqn7YQXH-ECIalATeOgF8dw-nU
----
evaluation result 5.0 , submission registered


## Ejercicio 2

Una matriz triangular 2D es aquella en la que cualquier elemento $m_{ij}=0 \iff i > j$, en donde $i$ son las filas y $j$ las columnas. Si asumimos que solamente trataremos con matrices cuadradas, es decir $\in \mathbb{R}^{n \times n}$.

Completa la siguiente función para que, dado un array `numpy` de entrada:

- Lance un `AssertError` si no es cuadrado o no es triangular superior
- Lance un `AssertError` si el parámetro `orientation` es distinto de `columns` o `rows`
- Devuelva un vector con las posiciones de almacenamiento de sus elementos, asumiendo una posición inicial y un tamaño de dato.
- Tenga en cuenta el parámetro `orientation` q

Por ejemplo, para esta entrada:

    [[ 1  2  6]
     [ 0  3  4]
     [ 0  0 -3]]

con `init_pos=19` y `size=5`, la salida debería de ser:

    [19 24 29 34 39 44]
    
observa que dada una matriz triangular superior $\in \mathbb{R}^{n\times n }$, el número de elementos que hay que almacenar viene dado por:

$$\frac{n^2 - n}{2} + n$$

ya que

- $n^2$ es el número total de elementos de la matriz
- $n^2-n$ es el número de elementos excluyendo la diagonal
- $\frac{n^2-n}{2}$ es el número de elementos de un triángulo (superior o inferion) excluyendo la diagonal
- $\frac{n^2 - n}{2} + n$ es el número de elementos de un triángulo incluyendo la diagonal

In [0]:
%%writefile ./utils/student_function/PS04_02.py
import numpy as np
def triang_store(m, init_pos=0, size=4, orientation="columns"):
    assert (m.shape[0]==m.shape[1]) 
    a=True
    for i in range (m.shape[0]-1):
        for j in range(m.shape[1]-1):
            if (i>j) and (m[i][j]!=0):
                a=False
    assert (a==True),"No es triangular"
    assert (orientation=="columns" or orientation=="rows")
    b=[init_pos]
    
    for i in range (m.shape[0]):
        for j in range(m.shape[1]-1):
            if (m[i][j]!=0):
                b+=[b[-1]+size]                    
            
    return b

Overwriting ./utils/student_function/PS04_02.py


comprueba manualmente tu código

In [0]:
import PS04_02 as st
reload(st)
import numpy as np
a = np.array([[1,4,3], [0,3,1], [0,0,-3]])
print a
print st.triang_store(a, init_pos=19, size=5)

[[ 1  4  3]
 [ 0  3  1]
 [ 0  0 -3]]
[19, 24, 24, 29]


#### comprueba tu código con el corrector automático

In [0]:
!./run CHECK_SOLUTION PS04_02

  File "<string>", line 31, in <module>
  File "./utils/student_function/PS04_02.py", line 9, in triang_store
    assert (a==True and (orientation=="columns" or orientation=="rows"))
checking your code with 100 random calls
<type 'exceptions.AssertionError'> 

** ERROR EJECUTANDO TU CODIGO **
evaluation result 0.0 


#### registra tu solución en línea

In [0]:
!./run SUBMIT_SOLUTION PS04_02

## Ejercicio 3

Dado:

- una especificación de dimensiones de un array $(d_0, d_1, ... d_{n-1})$ de $n$ dimensiones 
- una especificación de orden de almacenamiento $\mathbb{P}[0,1,..,n-1]$ (una permutación de los elementos del $0$ a $n-1$)
- una dirección de memoria de base (de inicio)
- un tamaño de dato


obtén la matriz de posiciones de memoria de cualquier array de tales dimensiones. **Tu salida ha de ser un array de `numpy`**

Por ejemplo, para

    dims = [2,2,2]
    order = [0,1,2]

la salida ha de ser

    [[[ 0 16]
      [ 8 24]]

     [[ 4 20]
      [12 28]]]
      
y para 

    dims = [2,3,4]
    order = [2,1,0]

la salida ha de ser

    [[[ 0  4  8 12]
      [16 20 24 28]
      [32 36 40 44]]

     [[48 52 56 60]
      [64 68 72 76]
      [80 84 88 92]]]
      
      
**Sugerencia**: usa la siguiente estrategia de implementación

1. Genera todas las posibles coordenadas de la matriz correspondiente a `dims`. Con esto deberías de generar un array de dimensiones $(\prod d_i)\times n$
2. Usa [`pandas.sort_values`](https://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.sort_values.html) para ordenar todas las posibles coordenadas según `order` (usa el parámetro `by`)
3. El dataframe generado anteriormente contiene en orden en el que se almacenarían en memoria los elementos de la matriz original según la especificación en `dims` y en  `order`
4. Genera una matriz de ceroz de tamaños `dims` y recorre secuencialmente el dataframe anterior actualizando cada coordenada.

In [0]:
%%writefile ./utils/student_function/PS04_03.py
import pandas as pd
import numpy as np
import itertools

def get_storage_positions(dims, order, size, init_pos=0):
    
    
    return <... TU CODIGO AQUI ...>

In [0]:
import PS04_03 as st
reload(st)
print st.get_storage_positions(dims = [2,3,4], order = [0,1,2], size=4)
print "--"
print st.get_storage_positions(dims = [2,3,4], order = [2,1,0], size=4)
print "--"
print st.get_storage_positions(dims = [2,2,2], order = [0,1,2], size=4)
print "--"
print st.get_storage_positions(dims = [2,2,2], order = [2,1,0], size=4)

#### comprueba tu código con el corrector automático

In [0]:
!./run CHECK_SOLUTION PS04_03

#### registra tu solución en línea

In [0]:
!./run SUBMIT_SOLUTION PS04_03

## Ejercicio 4

Dado un array de posiciones en memoria de $n$ dimensiones queremos descubrir qué ordenación tiene en memoria. Este ejercicio es el inverso del anterior.

Por ejemplo, dada la siguiente matriz de entrada


    [[[ 0  4  8 12]
      [16 20 24 28]
      [32 36 40 44]]

     [[48 52 56 60]
      [64 68 72 76]
      [80 84 88 92]]]
      
tu función ha de devolver la tupla 

    [2,1,0]
    
o con la siguiente matriz:

    [[[ 0  4  8 12]
      [32 36 40 44]
      [64 68 72 76]]

     [[16 20 24 28]
      [48 52 56 60]
      [80 84 88 92]]]
      
ha de devolver la tupla

    [2,0,1]
    
Sugerencia de implementación: para resolver este problema tienes que fijarte en el incremento en cada eje. Por ejemplo, fíjate en los dos primeros elementos de cada eje en la última matriz. Observa como el primer eje es el 2, el segundo el 0 y el último el 1.

In [0]:
import numpy as np
r = np.array([[[ 0,  4,  8, 12],
        [32, 36, 40, 44],
        [64, 68, 72, 76]],

       [[16, 20, 24, 28],
        [48, 52, 56, 60],
        [80, 84, 88, 92]]])

print r[:2,0,0]
print r[0,:2,0]
print r[0,0,:2]

In [0]:
ndims = 3
r = np.random.randint(100, size=[2]*ndims)
print r
mis_slices = [slice(0,2,None)]+[0]*(ndims-1)
print "--"
print r[mis_slices]

In [0]:
r[:2,0,0]

por tanto te sugiero una implementación en la que:
    
1. Hagas un bucle por el número de dimensiones
2. Para cada dimensión generes una lista de `slices` equivalentes a la notación de indexado anterior
3. Obtengas los dos primeros elementos de cada eje
4. Ordenes los ejes por la diferencia entre esos dos elementos

quizá la función [`np.argsort`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.argsort.html) pueda serte de ayuda

In [0]:
%%writefile ./utils/student_function/PS04_04.py
import numpy as np

def get_storage_order(r):
    
    
    return <... TU CODIGO AQUI ...>


comprueba manualmente tu código

In [0]:
import PS04_04 as st
reload(st)
r = np.array([[[ 0,  4,  8, 12],
        [32, 36, 40, 44],
        [64, 68, 72, 76]],

       [[16, 20, 24, 28],
        [48, 52, 56, 60],
        [80, 84, 88, 92]]])

st.get_storage_order(r)

#### comprueba tu código con el corrector automático

In [0]:
!./run CHECK_SOLUTION PS04_04

#### registra tu solución en línea

In [0]:
!./run SUBMIT_SOLUTION PS04_04

In [0]:
j=[1,2,3,4]
print j[1:]

[2, 3, 4]


In [0]:
a=True
import numpy as np
m = np.array([[1,4,3], [0,3,1], [0,0,-3]])
b=[4]
size=4
for i in range (m.shape[0]-1):
        for j in range(m.shape[1]):
            if (m[i][j]!=0):
                b+=[b[-1]+size]
print b                

[4, 8, 12, 16, 20, 24]
