## Taller de Ejemplo

## EJECUTA ESTA CELDA PARA AUTENTICARTE CON TU CUENTA DE GMAIL

In [1]:
!pip install -q oauth2client==1.5.2
from mooclib import *
import sys
sys.path.append("./utils/student_function/")
import inspect, urllib
html, auth_code, userinfo = google_authenticate(PORT_NUMBER=8080)
html

CLICK ON THIS LINK TO AUTHENTICATE WITH YOUR GMAIL ACCOUNT
https://accounts.google.com/o/oauth2/auth?scope=profile+email&redirect_uri=http%3A%2F%2Flocalhost%3A8080&response_type=code&client_id=486275613361-7nk9ktukfcfjevfoe3tamjp0pmbjmprs.apps.googleusercontent.com&access_type=offline
waiting for authentication ...
authentication succeeded


### Ejercicio 1: Suma dos matrices

Completa la función `suma_matrices` para que, dadas dos arrays numpy cualquiera devuelva la suma elemento a elemento.

#### Ejemplo de ejecución

    > s = np.array([1,2,3])
    > t = np.array([4,5,6])
    > suma_matrices(s,t)
    
      [5 7 9]
     

In [2]:
%%writefile ./utils/student_function/PS00_01.py

import numpy as np

def suma_matrices(a,b):
    ## --- TU CODIGO AQUI ---
    result = a+b
    return result


Writing ./utils/student_function/PS00_01.py


comprueba manualmente tu código

In [3]:
import PS00_01 as st
reload(st)
import numpy as np
a = np.random.randint(10, size=(3,2))
b = np.random.randint(10, size=(3,2))
print a
print b
print st.suma_matrices(a,b)

[[9 3]
 [9 6]
 [9 5]]
[[1 1]
 [0 9]
 [9 9]]
[[10  4]
 [ 9 15]
 [18 14]]


#### comprueba tu código con el corrector automático

In [4]:
!./run CHECK_SOLUTION PS00_01

checking your code with 100 random calls
** CORRECTO **
evaluation result 5.0 


#### registra tu solución en línea

In [5]:
!./run SUBMIT_SOLUTION PS00_01

connecting ... registering submission for daniel.riveraa@udea.edu.co ...
your personal submissions sheet for 20182-L3 was created, check your email
no config found for section PS00, allowing all submissions
checking your code with 100 random calls
** CORRECTO **
your submissions sheet is https://docs.google.com/spreadsheets/d/1QjA5eGBEkEfHxuQDJaqn7YQXH-ECIalATeOgF8dw-nU
----
evaluation result 5.0 , submission registered
