In [2]:
!pip install -q oauth2client==1.5.2
import sys
sys.path.append("./utils/student_function/")
from mooclib import *
import inspect, urllib
html, auth_code, userinfo = google_authenticate(PORT_NUMBER=8080)
html

CLICK ON THIS LINK TO AUTHENTICATE WITH YOUR GMAIL ACCOUNT
https://accounts.google.com/o/oauth2/auth?scope=profile+email&redirect_uri=http%3A%2F%2Flocalhost%3A8080&response_type=code&client_id=486275613361-7nk9ktukfcfjevfoe3tamjp0pmbjmprs.apps.googleusercontent.com&access_type=offline
waiting for authentication ...
authentication succeeded


vamos a implementar una matriz dispersa con una estructura de datos que nos permita realizar operaciones más eficientes. Representaremos una matriz como un **diccionario de diccionarios**. Es decir, usaremos un diccionario que, por cada fila, mantenga a su vez un diccionario indexado por columnas de valores de esa fila.

## Ejercicio 1.

Completa la función siguiente para que el diccionario `d` opere como un diccionario de diccionarios. Es decir, que cada `key1` del diccionario sea a su vez un diccionario de forma que al añadir un `item` con una `key2`  concreta:

1. si `d` no tiene ningún elemento en esa `key1` se cree un nuevo elemento con una diccionario vacío
1. se añada el `item` al diccionario referenciado con `d[key1][key2]`

observa que, dado un diccionario `d`:

- `d.keys()` devuelve la lista de claves
- `key in d.keys()` devuelve `True` si el diccionario ya contiente la clave `key` 

Ejemplo de ejecución:

    > d = {}
    > st.add_to_dict(d, 10, 3,  "20")
    > st.add_to_dict(d, 1, 5,  "4")
    > st.add_to_dict(d, 1, 2, "14")
    > print d
    > print d[1][5]

    {1: {2: '14', 5: '4'}, 10: {3: '20'}}
    4

In [2]:
%%writefile ./utils/student_function/PS03_01.py
def add_to_dict(d, key1, key2, val):
    if d.get(key1)==None:
        d[key1]={}
    d[key1][key2]=val  
    return d

Overwriting ./utils/student_function/PS03_01.py


comprueba manualmente tu código

In [3]:
import PS03_01 as st
reload(st)
d = {}
st.add_to_dict(d, 10, 3,  "20")
st.add_to_dict(d, 1, 5,  "4")
st.add_to_dict(d, 1, 2, "14")
print d

{1: {2: '14', 5: '4'}, 10: {3: '20'}}


observa que si los índices son números de files y columnas, accedemos a un elemento con una notación _matricial_ muy limpia

In [4]:
print d[1][5]

4


#### comprueba tu código con el corrector automático

In [5]:
!./run CHECK_SOLUTION PS03_01

checking your code with 100 random calls
** CORRECTO **
evaluation result 5.0 


#### registra tu solución en línea

In [7]:
!./run SUBMIT_SOLUTION PS03_01

connecting ... registering submission for daniel.riveraa@udea.edu.co ...
checking your code with 100 random calls
** CORRECTO **
your submissions sheet is https://docs.google.com/spreadsheets/d/1QjA5eGBEkEfHxuQDJaqn7YQXH-ECIalATeOgF8dw-nU
----
evaluation result 5.0 , submission registered


## Ejercicio 2

implementa el constructor de la siguiente clase y el método `sparseness_metric`

Observa que el constructor deberá:

- establecer el valor de `self.shape` al tamaño de la matrix `m`. Si `m` es `None` el tamaño ha de ser `(0,0)`
- rellenar el diccionario `self.rows` como un diccionario de diccionarios con los valores de `m` que sean distintos de 0. Tendrás que recorrer toda la matriz `m` para esto.

Ejemplo de ejecución:

    > m = array([[1, 0, 9],
    >       [0, 0, 7],
    >       [3, 5, 0],
    >       [5, 0, 0],
    >       [0, 3, 0]])
    >
    > s = st.SparseMatrix(m)
    > print "rows", s.rows
    > print "length of each row", [len(s.rows[i]) for i in s.rows.keys()]
    > print "sparseness metric", s.sparseness_metric()

    rows {0: {0: 1, 2: 9}, 1: {2: 7}, 2: {0: 3, 1: 5}, 3: {0: 5}, 4: {1: 3}}
    length of each row [2, 1, 2, 1, 1]
    sparseness metric 0.3333333

In [8]:
%%writefile ./utils/student_function/PS03_02.py
import itertools

def add_to_dict(d, key1, key2, val):
    if d.get(key1)==None:
        d[key1]={}
    d[key1][key2]=val 
    return d

class SparseMatrix:
    
    def __init__(self, m=None):
        self.rows = {}
        self.shape =m.shape if m is not None else(0,0)
        if m is not None:
            for i in range(m.shape[0]):
                for j in range(m.shape[1]):
                    if m[i,j]!=0:
                        add_to_dict(self.rows,i,j,m[i][j])
                           
    def sparseness_metric(self):
        j=0
        for i in self.rows.keys():
            j+=len(self.rows[i])

        metric = (j*1.)/(self.shape[0]*self.shape[1])
        return metric
        

Writing ./utils/student_function/PS03_02.py


comprueba manualmente tu código

In [9]:
import PS03_02 as st
reload(st)

import numpy as np

def random_sparse_matrix(size):
    m = np.random.randint(2, size=size)
    m = m * np.random.randint(10,size=size)
    return m
m = random_sparse_matrix((5,3))
print m.shape, st.SparseMatrix(m).sparseness_metric()
m

(5, 3) 0.4


array([[0, 2, 0],
       [8, 0, 8],
       [0, 0, 0],
       [4, 0, 0],
       [5, 0, 6]])

In [10]:
import PS03_02 as st
reload(st)

s = st.SparseMatrix(m)
print "rows", s.rows
print "length of each row", [len(s.rows[i]) for i in s.rows.keys()]

rows {0: {1: 2}, 1: {0: 8, 2: 8}, 3: {0: 4}, 4: {0: 5, 2: 6}}
length of each row [1, 2, 1, 2]


In [11]:
s = st.SparseMatrix(None)
s.shape

(0, 0)

#### comprueba tu código con el corrector automático

In [12]:
!./run CHECK_SOLUTION PS03_02

checking your code with 100 random calls
** CORRECTO **
evaluation result 5.0 


#### registra tu solución en línea

In [13]:
!./run SUBMIT_SOLUTION PS03_02

connecting ... registering submission for daniel.riveraa@udea.edu.co ...
checking your code with 100 random calls
** CORRECTO **
your submissions sheet is https://docs.google.com/spreadsheets/d/1QjA5eGBEkEfHxuQDJaqn7YQXH-ECIalATeOgF8dw-nU
----
evaluation result 5.0 , submission registered


## Ejercicio 3

implementa el método `to_dense` y el método `T` (por transpuesta). 

- `to_dense`: debe de devolver una matriz `numpy` equivalente a la propia matriz dispersa
- `T` ha de devolver una matriz dispersa nueva (una instancia nueva de la misma clase) con los índices de `self.rows` invertidos.

In [3]:
%%writefile ./utils/student_function/PS03_03.py
import itertools
import numpy as np

def add_to_dict(d, key1, key2, val):
    if d.get(key1)==None:
        d[key1]={}
    d[key1][key2]=val 
    return d

class SparseMatrix:
    
    def __init__(self, m=None):
        self.rows = {}
        self.shape = m.shape if m is not None else (0,0)
        self.nb_elements = 0
        
        if m is not None:
            for i in range(m.shape[0]):
                for j in range(m.shape[1]):
                    if m[i,j] != 0:
                        add_to_dict(self.rows, i, j, m[i,j])
                        self.nb_elements = self.nb_elements + 1
                           
    def to_dense(self):
        r = np.zeros(self.shape)
        for i in self.rows.keys():
            for j in self.rows[i].keys():
                r[i][j] = self.rows[i][j]
            
        return r
    
    def T(self):
        w = np.zeros((self.shape[1],self.shape[0]))
        for i in self.rows.keys():
            for j in self.rows[i].keys():
                w[j][i] = self.rows[i][j]
        r = self.__class__(w)        
        return r

Overwriting ./utils/student_function/PS03_03.py


comprueba manualmente tu código

In [5]:
import PS03_03 as st
reload(st)

def random_sparse_matrix(size):
    import numpy as np
    m = np.random.randint(2, size=size)
    m = m * np.random.randint(10,size=size)
    return m

m = random_sparse_matrix((5,3))
s = st.SparseMatrix(m)
print m

[[0 0 8]
 [0 3 0]
 [0 4 0]
 [1 0 0]
 [0 0 0]]


In [6]:
print m.T

[[0 0 0 1 0]
 [0 3 4 0 0]
 [8 0 0 0 0]]


In [7]:
print s.T().to_dense().astype(int)

[[0 0 0 1 0]
 [0 3 4 0 0]
 [8 0 0 0 0]]


#### comprueba tu código con el corrector automático

In [8]:
!./run CHECK_SOLUTION PS03_03

checking your code with 100 random calls
** CORRECTO **
evaluation result 5.0 


#### registra tu solución en línea

In [19]:
!./run SUBMIT_SOLUTION PS03_03

connecting ... registering submission for daniel.riveraa@udea.edu.co ...
checking your code with 100 random calls
** CORRECTO **
your submissions sheet is https://docs.google.com/spreadsheets/d/1QjA5eGBEkEfHxuQDJaqn7YQXH-ECIalATeOgF8dw-nU
----
evaluation result 5.0 , submission registered


## Ejercicio 4

Implementa el método `__getitem__` para que devuelva un elemento de la matriz dispersa con la misma notación que una matriz `numpy`. Ten en cuanta que:

- si `i` o `j` están fuera del tamaño de la matriz has de emitir un `AssertionError`
- si el elemento `(i,j)` existe en el diccionario interno (`self.rows`) se ha de devolver el valor almacenado
- si no existe, se ha de devolver el valor 0

In [27]:
%%writefile ./utils/student_function/PS03_04.py
import itertools

def add_to_dict(d, key1, key2, val):
    
    if key1 in d.keys():
            d[key1][key2] = val
    else:
        d[key1] = {key2: val}
    
    return d

class SparseMatrix:
    
    def __init__(self, m=None):
        
        self.rows = {}
        self.shape = m.shape if m is not None else (0,0)
        self.nb_elements = 0
        
        if m is not None:
            for i in range(m.shape[0]):
                for j in range(m.shape[1]):
                    if m[i,j] != 0:
                        add_to_dict(self.rows, i, j, m[i,j])
                        self.nb_elements = self.nb_elements + 1
    
    def __getitem__(self, (i,j)):
        
        assert i<= (self.shape[0]-1), "Indices fuera de la matriz"
        assert j<= (self.shape[1]-1), "Indices fuera de la matriz"
            
        for n in self.rows.keys():
            for m in self.rows[n].keys():
                if n == i and m == j:
                    return self.rows[n][m]
        return 0        


Overwriting ./utils/student_function/PS03_04.py


comprueba tu código manualmente

In [28]:
import PS03_04 as st
reload(st)

def random_sparse_matrix(size):
    m = np.random.randint(2, size=size)
    m = m * np.random.randint(10,size=size)
    return m

m = random_sparse_matrix((5,3))
print "original matrix shape", m.shape
print m

original matrix shape (5, 3)
[[3 1 6]
 [0 1 0]
 [7 6 0]
 [4 0 3]
 [6 8 7]]


In [29]:
import itertools
s = st.SparseMatrix(m)
print "inner dict", s.rows
print "\ncoord   value_in_m       value_in_s"
for i,j in itertools.product(range(m.shape[0]), range(m.shape[1])):                
    print "(%d,%d)   %5d        %5d"%(i,j, m[i,j], s[i,j])

inner dict {0: {0: 3, 1: 1, 2: 6}, 1: {1: 1}, 2: {0: 7, 1: 6}, 3: {0: 4, 2: 3}, 4: {0: 6, 1: 8, 2: 7}}

coord   value_in_m       value_in_s
(0,0)       3            3
(0,1)       1            1
(0,2)       6            6
(1,0)       0            0
(1,1)       1            1
(1,2)       0            0
(2,0)       7            7
(2,1)       6            6
(2,2)       0            0
(3,0)       4            4
(3,1)       0            0
(3,2)       3            3
(4,0)       6            6
(4,1)       8            8
(4,2)       7            7


#### comprueba tu código con el corrector automático

In [30]:
!./run CHECK_SOLUTION PS03_04

checking your code with 100 random calls
** CORRECTO **
evaluation result 5.0 


#### registra tu solución en línea

In [31]:
!./run SUBMIT_SOLUTION PS03_04

connecting ... registering submission for daniel.riveraa@udea.edu.co ...
checking your code with 100 random calls
** CORRECTO **
your submissions sheet is https://docs.google.com/spreadsheets/d/1QjA5eGBEkEfHxuQDJaqn7YQXH-ECIalATeOgF8dw-nU
----
evaluation result 5.0 , submission registered


## Ejercicio 5

Implementa el método `__setitem__` de forma que:

- si el valor del elemento es 0, no se haga nada
- si las coordenadas `i,j` exceden el tamaño actual de la matriz, se inserte el elemento, pero que se actualice el tamaño (`self.shape`) de manera acorde.


In [24]:
%%writefile ./utils/student_function/PS03_05.py
import itertools 
import numpy as np

def add_to_dict(d, key1, key2, val):
    if d.get(key1)==None:
        d[key1]={}
    d[key1][key2]=val 
    return d

class SparseMatrix:
    
    def __init__(self, m=None):
        
        self.rows = {}
        self.shape = m.shape if m is not None else (0,0)
        self.nb_elements = 0
        
        if m is not None:
            for i in range(m.shape[0]):
                for j in range(m.shape[1]):
                    if m[i,j] != 0:
                        add_to_dict(self.rows, i, j, m[i,j])
                        self.nb_elements = self.nb_elements + 1
    
    def __setitem__(self, (i,j), val):
        if val != 0:
            add_to_dict(self.rows, i, j, val)
            
            if i > (self.shape[0]-1):
                self.shape=((i+1),(self.shape[1]))
            
            if j > (self.shape[1]-1):
                self.shape=((self.shape[0]),(j+1))

    def __getitem__(self, (i,j)):
        
        assert i<= (self.shape[0]-1), "Indices fuera de la matriz"
        assert j<= (self.shape[1]-1), "Indices fuera de la matriz"
            
        for n in self.rows.keys():
            for m in self.rows[n].keys():
                if n == i and m == j:
                    return self.rows[n][m]
        return 0        


    def to_dense(self):
        r = np.zeros(self.shape)
        
        for i in self.rows.keys():
            for j in self.rows[i].keys():
                r[i][j] = self.rows[i][j]
            
        return r


Overwriting ./utils/student_function/PS03_05.py


comprueba manualmente tu código

In [26]:
import PS03_05 as st
reload(st)

def random_sparse_matrix(size):
    import numpy as np
    m = np.random.randint(2, size=size)
    m = m * np.random.randint(10,size=size)
    return m

m = random_sparse_matrix((5,3))
s = st.SparseMatrix(m)
print "initial"
print s.rows
print s.to_dense().astype(int)
s[4,2] = m[4,2]*2+3
print "\nafter __setitem__"
print s.rows
print s.to_dense().astype(int)


initial
{0: {2: 1}, 2: {0: 3, 1: 6}, 3: {1: 1}, 4: {2: 6}}
[[0 0 1]
 [0 0 0]
 [3 6 0]
 [0 1 0]
 [0 0 6]]

after __setitem__
{0: {2: 1}, 2: {0: 3, 1: 6}, 3: {1: 1}, 4: {2: 15}}
[[ 0  0  1]
 [ 0  0  0]
 [ 3  6  0]
 [ 0  1  0]
 [ 0  0 15]]


#### comprueba tu código con el corrector automático

In [27]:
!./run CHECK_SOLUTION PS03_05

checking your code with 100 random calls
** CORRECTO **
evaluation result 5.0 


#### registra tu solución en línea

In [37]:
!./run SUBMIT_SOLUTION PS03_05

connecting ... registering submission for daniel.riveraa@udea.edu.co ...
checking your code with 100 random calls
** CORRECTO **
your submissions sheet is https://docs.google.com/spreadsheets/d/1QjA5eGBEkEfHxuQDJaqn7YQXH-ECIalATeOgF8dw-nU
----
evaluation result 5.0 , submission registered


## Ejercicio 6

Implementa el método `__add__`

Sugerencia de implementación: 

1. verifique con un `assert` que ambas matrices son del mismo tamaño
1. crea una nueva matriz vacía
1. copie `self.shape` en el `shape` de la matriz nueva 
1. recorra todos los elementos de `self.rows` y llame al `__setitem__` de la matriz nueva por cada uno de ellos
1. recorra todos los elementos de `q` y haga un get/set sobre la nueva matriz para añadirlos


In [34]:
%%writefile ./utils/student_function/PS03_06.py
import itertools 
import numpy as np
def add_to_dict(d, key1, key2, val):    
    if key1 in d.keys():
            d[key1][key2] = val
    else:
        d[key1] = {key2: val}
    
    return d

class SparseMatrix:
    
    def __init__(self, m=None):
        self.rows = {}
        self.shape = m.shape if m is not None else (0,0)
        self.nb_elements = 0
        
        if m is not None:
            for i in range(m.shape[0]):
                for j in range(m.shape[1]):
                    if m[i,j] != 0:
                        add_to_dict(self.rows, i, j, m[i,j])
                        self.nb_elements = self.nb_elements + 1

    def to_dense(self):
        r = np.zeros(self.shape)
        
        for i in self.rows.keys():
            for j in self.rows[i].keys():
                r[i][j] = self.rows[i][j]
            
        return r
       
    def __getitem__(self, (i,j)):
        assert i<= (self.shape[0]-1), "Indices fuera de la matriz"
        assert j<= (self.shape[1]-1), "Indices fuera de la matriz"
            
        for n in self.rows.keys():
            for m in self.rows[n].keys():
                if n == i and m == j:
                    return self.rows[n][m]
                
        return 0
    
    def __setitem__(self, (i,j), val):
        if val != 0:
            add_to_dict(self.rows, i, j, val)
            
            if i > (self.shape[0]-1):
                self.shape=((i+1),(self.shape[1]))
            
            if j > (self.shape[1]-1):
                self.shape=((self.shape[0]),(j+1))

    def __add__ (self, q):
        assert self.shape[0] == q.shape[0] and self.shape[1] == q.shape[1], "No compatibles"
        r = self.__class__()
        r.shape = self.shape
        for i in self.rows.keys():
            for j in self.rows[i].keys():
                r[i,j] = self[i,j]      
        for i in q.rows.keys():
            for j in q.rows[i].keys():
                r[i,j] = r[i,j] + q[i,j]
        
        return r

Overwriting ./utils/student_function/PS03_06.py


In [35]:
import PS03_06 as st
reload(st)
m1 = random_sparse_matrix((5,3))
m2 = random_sparse_matrix((5,3)) 
sm1 = st.SparseMatrix(m1)
sm2 = st.SparseMatrix(m2)
print sm1.to_dense().astype(int)
print "--"
print sm2.to_dense().astype(int)

[[3 0 0]
 [1 0 2]
 [7 0 0]
 [0 0 4]
 [0 6 5]]
--
[[5 0 0]
 [1 0 0]
 [0 2 2]
 [0 4 0]
 [5 4 0]]


In [36]:
print (sm1+sm2).to_dense().astype(int)

[[ 8  0  0]
 [ 2  0  2]
 [ 7  2  2]
 [ 0  4  4]
 [ 5 10  5]]


In [37]:
print m1+m2

[[ 8  0  0]
 [ 2  0  2]
 [ 7  2  2]
 [ 0  4  4]
 [ 5 10  5]]


#### comprueba tu código con el corrector automático

In [38]:
!./run CHECK_SOLUTION PS03_06

checking your code with 100 random calls
** CORRECTO **
evaluation result 5.0 


#### registra tu solución en línea

In [39]:
!./run SUBMIT_SOLUTION PS03_06

connecting ... registering submission for daniel.riveraa@udea.edu.co ...
checking your code with 100 random calls
** CORRECTO **
your submissions sheet is https://docs.google.com/spreadsheets/d/1QjA5eGBEkEfHxuQDJaqn7YQXH-ECIalATeOgF8dw-nU
----
evaluation result 5.0 , submission registered


## Ejercicio 7

Implementa `dot` en nuestra clase de matrices dispersas representadas con un diccionario de diccionarios.

In [22]:
%%writefile ./utils/student_function/PS03_07.py

import itertools
import numpy as np
def add_to_dict(d, key1, key2, val):
    if key1 in d.keys():
            d[key1][key2] = val
    else:
        d[key1] = {key2: val}
    
    return d

class SparseMatrix:
    
    def __init__(self, m=None):
        self.rows = {}
        self.shape = m.shape if m is not None else (0,0)
        self.nb_elements = 0
        
        if m is not None:
            for i in range(m.shape[0]):
                for j in range(m.shape[1]):
                    if m[i,j] != 0:
                        add_to_dict(self.rows, i, j, m[i,j])
                        self.nb_elements = self.nb_elements + 1

    def to_dense(self):
        r = np.zeros(self.shape)
        
        for i in self.rows.keys():
            for j in self.rows[i].keys():
                r[i][j] = self.rows[i][j]
            
        return r
                        
    def __getitem__(self, (i,j)):
        assert i<= (self.shape[0]-1), "Indices fuera de la matriz"
        assert j<= (self.shape[1]-1), "Indices fuera de la matriz"
            
        for n in self.rows.keys():
            for m in self.rows[n].keys():
                if n == i and m == j:
                    return self.rows[n][m]
                
        return 0
    
    def __setitem__(self, (i,j), val):
        if val != 0:
            add_to_dict(self.rows, i, j, val)
            
            if i > (self.shape[0]-1):
                self.shape=((i+1),(self.shape[1]))
            
            if j > (self.shape[1]-1):
                self.shape=((self.shape[0]),(j+1))

    def __add__ (self, q):
        assert self.shape[0] == q.shape[0], "Matrices de diferente tamano"
        assert self.shape[1] == q.shape[1], "Matrices de diferente tamano"

        r = self.__class__()
        r.shape = self.shape
        
        for i in self.rows.keys():
            for j in self.rows[i].keys():
                r[i,j] = self[i,j]
                
        for i in q.rows.keys():
            for j in q.rows[i].keys():
                r[i,j] = r[i,j] + q[i,j]
        
        return r
    
    def dot(self, q):
        assert self.shape[1]==q.shape[0]
        
        
        r = self.__class__()
        r.shape = (self.shape[0] , q.shape[1])
        trans = q.T()
        
        for i in self.rows.keys():
            for j in trans.rows.keys():
                dot_product_one_point = 0
                for k in q.rows.keys():
                    tt = self.rows[i].get(k, 0)
                    dot_product_one_point = dot_product_one_point + tt * trans.rows[j].get(k, 0)
                r[i,j] = dot_product_one_point
        
        
              
        
        return r
    
    def sparseness_metric(self):
        metric = self.nb_elements*1./(self.shape[0]*self.shape[1])
        return metric
    
    def T(self):
        w = np.zeros((self.shape[1],self.shape[0]))
        for i in self.rows.keys():
            for j in self.rows[i].keys():
                w[j][i] = self.rows[i][j]
        
        r = self.__class__(w)
                
        return r

Overwriting ./utils/student_function/PS03_07.py


comprueba tu código manualmente 

In [23]:
import PS03_07 as st
reload(st)
import numpy as np
m1 = np.random.randint(10, size=(3,2))
print m1
m2 = np.random.randint(10, size=(2,3))
print m2
print "-- "
print m1.dot(m2)
print st.SparseMatrix(m1).dot(st.SparseMatrix(m2)).to_dense().astype(int)
print "--"
print m2.dot(m1)
print st.SparseMatrix(m2).dot(st.SparseMatrix(m1)).to_dense().astype(int)

[[5 2]
 [9 3]
 [6 9]]
[[7 5 9]
 [2 8 2]]
-- 
[[ 39  41  49]
 [ 69  69  87]
 [ 60 102  72]]
[[ 39  41  49]
 [ 69  69  87]
 [ 60 102  72]]
--
[[134 110]
 [ 94  46]]
[[134 110]
 [ 94  46]]


#### comprueba tu código con el corrector automático

In [24]:
!./run CHECK_SOLUTION PS03_07

checking your code with 100 random calls
** CORRECTO **
evaluation result 5.0 


#### registra tu solución en línea

In [25]:
!./run SUBMIT_SOLUTION PS03_07

connecting ... registering submission for daniel.riveraa@udea.edu.co ...
checking your code with 100 random calls
** CORRECTO **
your submissions sheet is https://docs.google.com/spreadsheets/d/1QjA5eGBEkEfHxuQDJaqn7YQXH-ECIalATeOgF8dw-nU
----
evaluation result 5.0 , submission registered


## Ejercicio 8

Realiza un algoritmo que devuelva el valor máximo de cada fila. Deberá de devolver una lista de tuplas `(row_nb, max_value)` solamente de las filas que contengan algún elemento. P.ej. de la siguiente matriz:

    [[4 0 0 0]
     [0 2 0 5]
     [0 2 0 0]
     [0 0 0 0]
     [0 6 0 0]
     [0 0 0 0]
     [0 0 0 6]
     [0 0 7 7]
     [0 0 2 7]
     [4 8 0 2]]
     
debe de devolver:

     [(0, 4), (1, 5), (2, 2), (4, 6), (6, 6), (7, 7), (8, 7), (9, 8)]

Este ejercicio debe de funcionar **con `SparseMatrix` de tu solución del ejercicio 3 anterior**


In [9]:
%%writefile ./utils/student_function/PS03_08.py
import numpy as np
def max_per_row(m):
    max_value = 0
    row_nb = int
    
    resultado = list([])
    
    for i in m.rows.keys():
        for j in m.rows[i].keys():
            if max_value < m.rows[i][j] and m.rows[i][j] != 0:
                max_value = m.rows[i][j]
                row_nb = i
        resultado.append((row_nb, max_value))
        max_value = 0
    
    return resultado

Overwriting ./utils/student_function/PS03_08.py


In [10]:
import PS03_08 as st
import PS03_03 as st3
reload(st)
m = random_sparse_matrix((10,4))
s = st3.SparseMatrix(m)
print m
print st.max_per_row(s)

[[0 0 0 5]
 [5 0 4 9]
 [0 0 0 0]
 [0 9 0 0]
 [5 0 0 0]
 [0 0 0 3]
 [0 0 0 0]
 [8 9 0 0]
 [6 0 0 6]
 [3 0 0 0]]
[(0, 5), (1, 9), (3, 9), (4, 5), (5, 3), (7, 9), (8, 6), (9, 3)]


In [11]:
mm = m.max(axis=1)
w = np.argwhere(mm!=0)[:,0]
np.allclose(np.r_[[(i,j) for i,j in zip(w, mm[w])]], np.r_[st.max_per_row(s)])

NameError: name 'np' is not defined

#### comprueba tu código con el corrector automático

In [12]:
!./run CHECK_SOLUTION PS03_08

checking your code with 100 random calls
** CORRECTO **
evaluation result 5.0 


#### registra tu solución en línea

In [13]:
!./run SUBMIT_SOLUTION PS03_08

connecting ... registering submission for daniel.riveraa@udea.edu.co ...
checking your code with 100 random calls
** CORRECTO **
your submissions sheet is https://docs.google.com/spreadsheets/d/1QjA5eGBEkEfHxuQDJaqn7YQXH-ECIalATeOgF8dw-nU
----
evaluation result 5.0 , submission registered


## Ejercicio 9

Realiza un algoritmo que devuelva el valor máximo de cada columna. Deberá de devolver una lista de tuplas `(col_nb, max_value)` solamente de las columnas que contengan algún elemento. P.ej. de la siguiente matriz:

        [[0 0 2 0 0 1 0 0 0 1]
         [5 3 0 4 0 0 0 5 0 2]
         [9 0 0 4 0 0 0 0 0 0]]
 
 
deberá devolver el siguiente resultado:

        [(0, 9), (1, 3), (2, 2), (3, 4), (5, 1), (7, 5), (9, 2)]
        
 Este ejercicio debe de funcionar **con `SparseMatrix` de tu solución del ejercicio 3 anterior**


In [14]:
%%writefile ./utils/student_function/PS03_09.py
import numpy as np
def max_per_col(m):
    max_value = 0
    col_nb = int
    resultado = list([])
    
    for i in range(m.shape[1]):
        col_nb = i
        for j in range(m.shape[0]):
            if j in m.rows.keys():
                if i in m.rows[j].keys():
                    if max_value < m.rows[j][i] and m.rows[j][i] != 0:
                        max_value = m.rows[j][i]
        if max_value != 0:
            resultado.append((col_nb, max_value))
        max_value = 0
        
    return resultado

Overwriting ./utils/student_function/PS03_09.py


In [15]:
import PS03_09 as st
import PS03_03 as st3
reload(st)
m = st3.SparseMatrix(random_sparse_matrix((3,10)))
print m.to_dense().astype(int)
print st.max_per_col(m)

[[4 0 0 8 9 9 8 5 7 0]
 [6 0 1 0 0 0 2 0 2 7]
 [5 0 0 4 0 9 3 0 9 0]]
[(0, 6), (2, 1), (3, 8), (4, 9), (5, 9), (6, 8), (7, 5), (8, 9), (9, 7)]


#### comprueba tu código con el corrector automático

In [16]:
!./run CHECK_SOLUTION PS03_09

checking your code with 100 random calls
** CORRECTO **
evaluation result 5.0 


#### registra tu solución en línea

In [17]:
!./run SUBMIT_SOLUTION PS03_09

connecting ... registering submission for daniel.riveraa@udea.edu.co ...
checking your code with 100 random calls
** CORRECTO **
your submissions sheet is https://docs.google.com/spreadsheets/d/1QjA5eGBEkEfHxuQDJaqn7YQXH-ECIalATeOgF8dw-nU
----
evaluation result 5.0 , submission registered


## Análisis de complejidad computacional

ya acabaste el taller. Ahora si quieres, puedes jugar con tus soluciones y ejecutar las siguientes celdas para medir experimentalmente la complejidad computacional de tus soluciones. Compárala con la de la implementación de las notas.

In [ ]:
import PS03_07 as st
reload(st)
def xrandom_sparse_matrix(max_rows, max_cols, n_items):
    m = st7.SparseMatrix()
    for _ in xrange(n_items):
        i = np.random.randint(max_rows)
        j = np.random.randint(max_cols)
        v = np.random.randint(100)
        m[i,j] = v
    return m

In [ ]:
k=xrandom_sparse_matrix(1000,1000,1000)
k.shape, k.sparseness_metric()

In [ ]:
import matplotlib.pyplot as plt
%matplotlib inline
def plot_times(n_set, r, xlabel, ylabel):
    from scipy.optimize import minimize

    n_set = np.array(n_set)
    # fit to scaled for numerical stability
    x_ticks = n_set/1e3
    r     = np.array(r)
    cfunc = lambda k, x: k[0]+k[1]*x+k[2]*x**2+k[3]*x**3
    qfunc = lambda k, x: k[0]+k[1]*x+k[2]*x**2
    lfunc = lambda k, x: k[0]+k[1]*x
    ccost = lambda k: np.mean( (r-cfunc(k, x_ticks))**2)
    qcost = lambda k: np.mean( (r-qfunc(k, x_ticks))**2)
    lcost = lambda k: np.mean( (r-lfunc(k, x_ticks))**2)
    cx    = minimize(ccost, [0,0,0,0], method="BFGS").x
    qx    = minimize(qcost, [0,0,0], method="BFGS").x
    lx    = minimize(lcost, [0,0], method="BFGS").x
    
    plt.plot(x_ticks*1e3, cfunc(cx, x_ticks), label="cubic fit", color="black")
    plt.plot(x_ticks*1e3, qfunc(qx, x_ticks), label="quadratic fit", color="black", ls="--")
    plt.plot(x_ticks*1e3, lfunc(lx, x_ticks), label="linear fit", color="black", ls=":")
    plt.plot(x_ticks*1e3, r, label="data", lw=10, alpha=.5, color="red")
    plt.legend()
    plt.xlabel(xlabel)
    plt.ylabel(ylabel)
    plt.grid()  

## `__setitem__`

In [ ]:
r2 = []
n2 = range(50,3000,100)
for n in n2:
    print n,
    k = %timeit -o -q -r 3 -n 3 xrandom_sparse_matrix(200,200,n)
    r2.append(k.best)

In [ ]:
plot_times(n2, r2, xlabel="number of triplets", ylabel="time for 200x200 matrix")

## `__getitem__`

In [ ]:
r1 = []
n1 = range(50,3000,100)
def getn(m,n):
    for i in m.rows.keys():
        for j in m.rows[i].keys():
            m[i,j]
    
for n in n1:
    print n,
    m = xrandom_sparse_matrix(200,200,n)
    k = %timeit -o -q -r 3 -n 3 getn(m,n)
    r1.append(k.best)

In [ ]:
plot_times(n1, r1, xlabel="number of triplets", ylabel="time for 200x200 matrix")

## `__add__`

In [ ]:
r3 = []
n3 = range(50,3000,100)
for n in n3:
    print n,
    m1 = xrandom_sparse_matrix(200,200,n)
    m2 = xrandom_sparse_matrix(200,200,n)
    m1[200,200]=1
    m2[200,200]=1
    k = %timeit -o -q -r 3 -n 3 m1+m2
    r3.append(k.best)
plot_times(n3, r3,xlabel="number of triplets", ylabel="time for 200x200 matrix")

## `dot`

In [ ]:
r4 = []
n4 = range(50,3000,200)
for n in n4:
    print n,
    m = xrandom_sparse_matrix(200,200,n)
    k = %timeit -o -q -r 3 -n 3 m.dot(m.T())
    r4.append(k.best)
plot_times(n4, r4,xlabel="number of triplets", ylabel="time for 200x200 matrix")